version: '3.8'
services:
  web:
    image: nginx:stable-alpine
    container_name: web
    restart: always
    ports:
      - '8000:80'
    depends_on:
      - app
    volumes:
      - .:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - seguro_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - .:/var/www/html:rw
    networks:
      - seguro_net

networks:
  seguro_net:
    driver: bridge